spring:
  datasource:
    # 驱动类名称
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库连接的url
    url: jdbc:mysql://localhost:3306/imbr-label
    # 连接数据库的用户名
    username: root
    # 连接数据库的密码
    password: 1234
  data:
    redis:
      database: 0
      port: 6379
      host: localhost
      password: 1234
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
      file-size-threshold: 2MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis:
  configuration:
    # 设置驼峰命名自动映射
    map-underscore-to-camel-case: true
    # 配置mybatis的日志，指定输出到控制台
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
file:
  upload-dir: C:\\Users\\zhaoyue\\.imbr\\upload\\

label:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: itcast
    # 设置jwt过期时间
    admin-ttl: 2592000000
    # 设置前端传递过来的令牌名称
    admin-token-name: Authorization