spring:
  datasource:
    # 驱动类名称
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库连接的url
    url: jdbc:mysql://localhost:3306/imbr-label
    # 连接数据库的用户名
    username: root
    # 连接数据库的密码
    password: 123456
  data:
    redis:
      database: 0
      port: 6379
      host: 192.168.232.129
      password: 123456
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

mybatis:
  configuration:
    # 设置驼峰命名自动映射
    map-underscore-to-camel-case: true
    # 配置mybatis的日志，指定输出到控制台
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
file:
  upload-dir: C:/Users/wangy/.imbr/upload/

label:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: itcast
    # 设置jwt过期时间
    admin-ttl: 2592000000
    # 设置前端传递过来的令牌名称
    admin-token-name: Authorization